/**
 * Regenerates src/version.ts from package.json so the User-Agent header the
 * SDK sends always matches the published version. Runs automatically inside
 * the `version-packages` script (i.e. whenever changesets bumps the version);
 * a unit test in test/client.test.ts fails if the two ever drift.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

const content = `// Generated by scripts/sync-version.mjs — do not edit by hand.
export const VERSION = '${pkg.version}'
`

writeFileSync(new URL('../src/version.ts', import.meta.url), content)
console.log(`src/version.ts -> ${pkg.version}`)
